### ISSUE TITLE
Look into Django

### ISSUE THREAD

**Issue by emlala** [emlala/emmiagata#8]

**Comment by emlala** [comment]
Hi Agata, have you had time to look into this? If you've ran into problems we still have a couple of days so I could try to help :)

- Emmi

**Comment by aadomino** [comment]
I've tried writing a Django web app, but since I had to leave Finland earlier than expected, it's not really in an uploadable condition :) I've been advised that for this application a simpler solution could work, I looked into http://webpy.org/docs/0.3/tutorial and used this one. I uploaded a version of the program now.
